version: '2'

networks:
  ccdashboardplatform_prodnetwork:
    external: true

services:
  timesheet-service:
    container_name: timesheet-service
    image: ccd-timesheet-service
    ports:
      - "10005:8080"
    mem_limit: "3G"
    expose:
      - "8080"
    networks:
      - ccdashboardplatform_prodnetwork
    links:
      - cassandra:cassandra
    mem_limit: "1536m"
  cassandra:
    build: ./DockerCassandra
    mem_limit: "3G"
    expose:
      - "9042"
    networks:
      - ccdashboardplatform_prodnetwork
    volumes:
      - data:/var/lib/cassandra
     mem_limit: "1024m"

volumes:
  data:
    driver: local
