version: '2'

networks:
  ccdashboardplatform_prodnetwork:
    external: true

services:
  timesheet-service:
    container_name: timesheet-service
    image: ccd-timesheet-service
    ports:
      - "10005:8080"
    networks:
      - ccdashboardplatform_prodnetwork
    links:
      - cassandra:cassandra
  cassandra:
    build: ./DockerCassandra
    expose:
      - "9042"
    networks:
      - ccdashboardplatform_prodnetwork
    volumes:
      - data:/var/lib/cassandra

volumes:
  data:
    driver: local
